server.port: 8765
datasource:
  railvideo_db:
    url: jdbc:mysql://localhost:3306/rv
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: false
      format_sql: false
      dialect: org.hibernate.dialect.MySQLDialect

rv:
  sensors:
    track_period_sec: 3600
    buffer_size: 1024
  alarms:
    alarm_lifetime_sec: 3600